### ISSUE TITLE
Hand History Format?

### ISSUE THREAD

**Issue by ludkiller** [pokerregion/poker#11]
What is the format of hand history parsable by this API? 
can you link me to the docs if there's any ?
other than http://en.wikipedia.org/wiki/Hand_history

**Comment by kissgyorgy** [comment]
Hi! You can find it in the tests, here: 
https://github.com/pokerregion/poker/blob/master/tests/handhistory/ftp_hands.py
It seemed a good idea to put those in `.py` files like this :smile: 
Basically current PokerStars, Full Tilt Poker and PKR handhistories should be recognized. Not every type though.

**Comment by ludkiller** [comment]
thanks :3
