### ISSUE TITLE
enum problem

### ISSUE THREAD

**Issue by rpg32** [pokerregion/poker#22]
I just started playing with this code a bit and I am running into an issue. I cannot refer to suits as 'c' or 's' etc.

If I try to make a combo it does not understand '2s3d' for example. It says "ValueError: s is not a valid Suit"

So it seems like the enum coding that provides the 'c' or 'clubs' equivalent references is not working for some reason.

Any idea why this is happening?

---

A bit more info...
The error occurs in the code within the __common.py file on line 29 with the return statement:  

'return super(_PokerEnumMeta, cls).__call__(value)'

which causes the **init**.py of enum to call the following function on line 330:

cls.**new**(cls, value)

and finally having the error in that same file on line 642 with the following try/except code:

```
try:
    if value in cls._value2member_map_:
        return cls._value2member_map_[value]
except TypeError:
    # not there, now do long search -- O(n) behavior
    for member in cls._member_map_.values():
        if member.value == value:
            return member
raise ValueError("%s is not a valid %s" % (value, cls.__name__))
```

which raises the ValueError and outputs:

ValueError: s is not a valid Suit

...

ok, last edit... 

It looks like capital letters work for suits but not lowercase. So I can successfully call Card('AS') but not Card('As')

Thanks

**Comment by kissgyorgy** [comment]
This is definetely a bug, see #20. I will fix it, but until then use unicode_literals future or try `Card(u'As')` instead of `Card('As')`

**Comment by kissgyorgy** [comment]
The codebase is now Python 3 only.
