### ISSUE TITLE
Pokerstars Parsing Error

### ISSUE THREAD

**Issue by IIAmonII** [pokerregion/poker#25]
Hello,
at first I really like your project and the ideas behind it.
As I was using it i got this error on my own PokerStarsHandHistory (Zoom)

![errror](https://cloud.githubusercontent.com/assets/19474116/15398777/55ca8dd0-1de5-11e6-9b93-4ef743364a7e.png)

How can I fix this bug?

**Comment by kissgyorgy** [comment]
If your pull request doesn't solve this, please attach the problematic hand if you can.
