### ISSUE TITLE
'J' is not a valid Rank

### ISSUE THREAD

**Issue by connormclaud** [pokerregion/poker#27]
` from poker import Suit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/poker/__init__.py", line 10, in <module>
    from poker.card import Suit, Rank, Card, FACE_RANKS, BROADWAY_RANKS
  File "/usr/local/lib/python3.5/dist-packages/poker/card.py", line 51, in <module>
    FACE_RANKS = Rank('J'), Rank('Q'), Rank('K')
  File "/usr/lib/python3.5/enum.py", line 235, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.5/enum.py", line 470, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'J' is not a valid Rank`

Just after installing for Python 3.5.1 on Ubuntu Linux

**Comment by kissgyorgy** [comment]
https://poker.readthedocs.io/en/latest/development.html#about-the-state-of-python3

**Comment by connormclaud** [comment]
you can simply prevent installing in Python 3 via pip script instead of throwing strange errors at runtime. 
This issue is not about Python 3 support but about runtime errors which is not clear

**Comment by kissgyorgy** [comment]
Here is the setup.py:
https://github.com/pokerregion/poker/blob/master/setup.py#L26-L31
Python3 is not listed.

**Comment by connormclaud** [comment]
unfortunately this doesn't prevent pip from installing in Python 3. Something like this should work:
`if not sys.version_info[0] == 2:
    sys.exit("Sorry, Python 3 is not supported (yet)")`
