### ISSUE TITLE
ValueError: 'J' is not a valid Rank

### ISSUE THREAD

**Issue by snarb** [pokerregion/poker#32]
During library initialization I got

>  ValueError: 'J' is not a valid Rank

on [BROADWAY_RANKS = Rank('T'), Rank('J'), Rank('Q'), Rank('K'), Rank('A')](https://github.com/pokerregion/poker/blob/master/poker/card.py#L53)

Python3 installed fusing pip.

**Comment by kissgyorgy** [comment]
If you don't care, why should I? https://poker.readthedocs.io/en/latest/development.html#about-the-state-of-python3
